spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webflux
  thymeleaf:
    prefix: classpath:/templates/
server:
  port: 8081
  tomcat:
    max-threads: 3
    max-connections: 3
